config/routes.rb
Rails.application.routes.draw do
  resources :interventions
  resources :leads
  devise_for :users
  resources :quotes
  get 'website/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'website#index'
  
  get '/index', to: 'website#index'
  
  get '/residential', to: 'website#residential'

  get '/commercial', to: 'website#commercial'

  get '/quote', to: 'website#quote'

  get '/intervention', to: 'website#intervention'

  get '/trivia', to: 'website#trivia'

  get '/machineLearning', to: 'website#machineLearning'

  get '/google', to: 'google#maps'

  post '/watson/greetings', to: 'watson#greetings'

  get 'building_select/:customerID', to: 'interventions#building_select'

  get 'battery_select/:buildingID', to: 'interventions#battery_select'

  get 'column_select/:batteryID', to: 'interventions#column_select'

  get 'elevator_select/:columnID', to: 'interventions#elevator_select'

end


app/models/intervention.rb
class Intervention < ApplicationRecord
    validates :customerID, presence: true
    validates :buildingID, presence: true

    # after_create :ticket_create_contact
    # require 'zendesk_api'

    # def ticket_create_contact
    #     client = ZendeskAPI::Client.new do |config|
    #         # Mandatory:
          
    #         config.url = "https://schooltest.zendesk.com/api/v2" # e.g. https://rocketelevator8148.zendesk.com/api/v2
          
    #         # Basic / Token Authentication
    #         config.username = "dontcanceltrial@hotmail.com"
            
          
    #         # Choose one of the following depending on your authentication choice
    #         config.token = ENV["ZENDESK_APIKEY"]
          
    #       #   # OAuth Authentication
    #       #   config.access_token = "your OAuth access token"
          
    #         # Optional:
          
    #         # Retry uses middleware to notify the user
    #         # when hitting the rate limit, sleep automatically,
    #         # then retry the request.
    #         config.retry = true
          
    #         # Raise error when hitting the rate limit.
    #         # This is ignored and always set to false when `retry` is enabled.
    #         # Disabled by default.
    #         config.raise_error_when_rate_limited = false
          
    #         # Logger prints to STDERR by default, to e.g. print to stdout:
    #         require 'logger'
    #         config.logger = Logger.new(STDOUT)
          
    #         # Disable resource cache (this is enabled by default)
    #         config.use_resource_cache = false
          
    #         # Changes Faraday adapter
    #         # config.adapter = :patron
          
    #         # Merged with the default client options hash
    #         # config.client_options = {:ssl => {:verify => false}, :request => {:timeout => 30}}
          
    #         # When getting the error 'hostname does not match the server certificate'
    #         # use the API at https://yoursubdomain.zendesk.com/api/v2
    #     end
    #     # ticket = ZendeskAPI::Ticket.new("#{client}", :id => 1, :priority => "urgent")
    #     firstname = Employee.find("#{author}").first_name
    #     lastname = Employee.find("#{author}").last_name
    #     customer = Customer.find("#{customerID}").compagny_name
    #     if employeeID == nil
    #         firstname1 = "None"
    #         lastname1 = ""
    #     else
    #         firstname1 = Employee.find("#{employeeID}").first_name
    #         lastname1 = Employee.find("#{employeeID}").last_name
    #     end

    #     puts "This is the client after creation #{client}"
    #     client.tickets.create(
    #         :subject => "Intervention", 
    #         :comment => { :value => "An intervention request has been sent. Here are the details provided by the employee:
    #         Requester: #{firstname} #{lastname}
    #         Customer: #{customer}
    #         Building ID: #{buildingID}
    #         Battery ID (if applicable): #{batteryID}
    #         Column ID (if applicable): #{columnID}
    #         Elevator ID (if applicable): #{elevatorID}
    #         Employee assigned to the task (if applicable): #{firstname1} #{lastname1}
    #         Description of the request: #{report}" }, 
    #         :submitter_id => client.current_user.id, 
    #         :type => "problem",
    #         :priority => "urgent")
    #     puts "Ticket creation?"
    #     client.tickets.save
    #     puts "Ticket saved?"
    # end
end

app/controllers/interventions_controller.rb
class InterventionsController < ApplicationController
  before_action :set_intervention, only: %i[ show edit update destroy ]

  # GET /interventions or /interventions.json
  def index
    redirect_to index_url
    @interventions = Intervention.all
  end

  # GET /interventions/1 or /interventions/1.json
  def show
    redirect_to index_url
  end

  # GET /interventions/new
  def new
    redirect_to index_url
    @intervention = Intervention.new
  end

  # GET /interventions/1/edit
  def edit
    redirect_to index_url
  end

  # POST /interventions or /interventions.json
  def create
    @intervention = Intervention.new(intervention_params)

    respond_to do |format|
      if @intervention.save
        format.html { redirect_to index_url, notice: "Intervention was successfully created." }
        format.json { render :show, status: :created, location: @intervention }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interventions/1 or /interventions/1.json
  def update
    respond_to do |format|
      if @intervention.update(intervention_params)
        format.html { redirect_to index_url, notice: "Intervention was successfully updated." }
        format.json { render :show, status: :ok, location: @intervention }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interventions/1 or /interventions/1.json
  def destroy
    @intervention.destroy
    respond_to do |format|
      format.html { redirect_to index_url, notice: "Intervention was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def building_select
    puts "Entered controller"
    @buildings = Building.where("customer_id = ?", params[:customerID])
    if request.xhr?
        respond_to do |format|
            format.json { render :json => @buildings }
          end
      end
  end
  def battery_select
    puts "Entered controller"
    @batteries = Battery.where("building_id = ?", params[:buildingID])
    if request.xhr?
        respond_to do |format|
            format.json { render :json => @batteries }
          end
      end
  end
  def column_select
    puts "Entered controller"
    @columns = Column.where("battery_id = ?", params[:batteryID])
    if request.xhr?
        respond_to do |format|
            format.json { render :json => @columns }
          end
      end
  end
  def elevator_select
    puts "Entered controller"
    @elevators = Elevator.where("column_id = ?", params[:columnID])
    if request.xhr?
        respond_to do |format|
            format.json { render :json => @elevators }
          end
      end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intervention
      redirect_to index_url
      @intervention = Intervention.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def intervention_params
      params.require(:intervention).permit(:author, :customerID, :buildingID, :batteryID, :columnID, :elevatorID, :employeeID, :start_date_and_time_of_the_intervention, :end_date_and_time_of_the_intervention, :result, :report, :status)
    end
end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/views/interventions/_form.html.erb
<%= form_with(model: intervention, local: true)  do |form| %>
  <% if intervention.errors.any? %>
    <div class="col-md-12 text-center" id="error_explanation">
      <h2><%= pluralize(intervention.errors.count, "error") %> prohibited this intervention from being saved:</h2>

      <ul>
      <% intervention.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field" style="display: none;">
    <%= form.label :author %>
    <%= form.text_field :author, value:current_user.employee.id %>
  </div>

  <div class="field" >
    <%= form.label(:customerID, "Select a Customer") %>
    <%= form.select :customerID, Customer.all.collect {|c| [c.compagny_name, c.id]}, {include_blank: true}, :required => 'required',  :class => "col-md-2 text-center" %>
  </div>

  <div class="field" id="buildingDiv">
    <%= form.label(:buildingID, "Select a Building") %>
    <%= form.select :buildingID, Building.all.collect {|b| [b.id, b.id]}, {include_blank: true}, :required => 'required',  :class => "col-md-2 text-center" %>
  </div>

  <div class="field" id="batteryDiv">
    <%= form.label(:batteryID, "Select a Battery if applicable") %>
    <%= form.select :batteryID, Battery.all.collect {|p| [p.id, p.id]}, {include_blank: true}, :class => "col-md-2 text-center" %>
  </div>

  <div class="field" id="columnDiv">
    <%= form.label(:columnID, "Select a Column if applicable") %>
    <%= form.select :columnID, Column.all.collect {|p| [p.id, p.id]}, {include_blank: true}, :class => "col-md-2 text-center" %>
  </div>

  <div class="field" id="elevatorDiv">
    <%= form.label(:elevatorID, "Select an Elevator if applicable") %>
    <%= form.select :elevatorID, Elevator.all.collect {|p| [p.id, p.id]}, {include_blank: true},  :class => "col-md-2 text-center" %>
  </div>

  <div class="field">
    <%= form.label(:employeeID, "Select an Employee") %>
    <%= form.select :employeeID, Employee.all.collect {|e| [e.first_name + " " + e.last_name, e.id]}, {include_blank: "None"},  :class => "col-md-2 text-center" %>
  </div>

  <div class="field" style="display: none;">
    <%= form.label :start_date_and_time_of_the_intervention %>
    <%= form.text_field :start_date_and_time_of_the_intervention, value:nil %>
  </div>

  <div class="field" style="display: none;">
    <%= form.label :end_date_and_time_of_the_intervention %>
    <%= form.text_field :end_date_and_time_of_the_intervention, value:nil %>
  </div>

  <div class="field" style="display: none;">
    <%= form.label :result %>
    <%= form.text_field :result, value:"Incomplete" %>
  </div>

  <div class="field">
    <%= form.label(:report, "Description") %>
    <%= form.text_area :report, :class => "col-md-2", :required => 'required' %>
  </div>

  <div class="field" style="display: none;">
    <%= form.label :status %>
    <%= form.text_field :status, value:"Pending"%>
  </div>

  <div class="actions">
    <%= form.submit class: 'col-md-2 btn btn-primary', value:"Submit" %>
  </div>
<% end %>

app/views/interventions/edit.html.erb
<h1>Editing Intervention</h1>

<%= render 'form', intervention: @intervention %>

<%= link_to 'Show', @intervention %> |
<%= link_to 'Back', interventions_path %>

app/views/interventions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interventions</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Customerid</th>
      <th>Buildingid</th>
      <th>Batteryid</th>
      <th>Columnid</th>
      <th>Elevatorid</th>
      <th>Employeeid</th>
      <th>Start date and time of the intervention</th>
      <th>End date and time of the intervention</th>
      <th>Result</th>
      <th>Report</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interventions.each do |intervention| %>
      <tr>
        <td><%= intervention.author %></td>
        <td><%= intervention.customerID %></td>
        <td><%= intervention.buildingID %></td>
        <td><%= intervention.batteryID %></td>
        <td><%= intervention.columnID %></td>
        <td><%= intervention.elevatorID %></td>
        <td><%= intervention.employeeID %></td>
        <td><%= intervention.start_date_and_time_of_the_intervention %></td>
        <td><%= intervention.end_date_and_time_of_the_intervention %></td>
        <td><%= intervention.result %></td>
        <td><%= intervention.report %></td>
        <td><%= intervention.status %></td>
        <td><%= link_to 'Show', intervention %></td>
        <td><%= link_to 'Edit', edit_intervention_path(intervention) %></td>
        <td><%= link_to 'Destroy', intervention, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intervention', new_intervention_path %>

app/views/interventions/new.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<link rel="icon" type="image/png" href="<%= asset_path('faviconlogo.png') %>" />
		<meta charset="utf-8" />
		<title>Interventions Form-Rocket Elevators</title>
		<meta name="description" content="" />
		<meta name="Author" content="Dorin Grigoras [www.stepofweb.com]" />

		<!-- mobile settings -->
		<meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />
		<!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->

		<!-- WEB FONTS : use %7C instead of | (pipe) -->
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600%7CRaleway:300,400,500,600,700%7CLato:300,400,400italic,600,700" rel="stylesheet" type="text/css" />

	</head>

	<!--
		AVAILABLE BODY CLASSES:
		
		smoothscroll 			= create a browser smooth scroll
		enable-animation		= enable WOW animations

		bg-grey					= grey background
		grain-grey				= grey grain background
		grain-blue				= blue grain background
		grain-green				= green grain background
		grain-blue				= blue grain background
		grain-orange			= orange grain background
		grain-yellow			= yellow grain background
		
		boxed 					= boxed layout
		pattern1 ... patern11	= pattern background
		menu-vertical-hide		= hidden, open on click
		
		BACKGROUND IMAGE [together with .boxed class]
	
	-->
	<body>

		<!-- wrapper -->
		<div id="wrapper">

			<!-- 
				AVAILABLE HEADER CLASSES

				Default nav height: 96px
				.header-md 		= 70px nav height
				.header-sm 		= 60px nav height

				.b-0 		= remove bottom border (only with transparent use)
				.transparent	= transparent header
				.translucent	= translucent header
				.sticky			= sticky header
				.static			= static header
				.dark			= dark header
				.bottom			= header on bottom
				
				shadow-before-1 = shadow 1 header top
				shadow-after-1 	= shadow 1 header bottom
				shadow-before-2 = shadow 2 header top
				shadow-after-2 	= shadow 2 header bottom
				shadow-before-3 = shadow 3 header top
				shadow-after-3 	= shadow 3 header bottom

				.clearfix		= required for mobile menu, do not remove!

				Example Usage:  class="clearfix sticky header-sm transparent b-0"
			-->
			<div id="header" class="navbar-toggleable-md sticky clearfix">

				<!-- TOP NAV -->
				<header id="topNav">
					<div class="container">

						<!-- Mobile Menu Button -->
						<button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
							<i class="fa fa-bars"></i>
						</button>

						<!-- Logo -->
						<a class="logo float-left scrollTo" href="#top" style="background-color: #FFFFFF">
							<img src="<%= asset_path('R2.png') %>" alt="" />
						</a>

						<!-- 
							Top Nav 
							
							AVAILABLE CLASSES:
							submenu-dark = dark sub menu
						-->
						<div class="navbar-collapse collapse float-right nav-main-collapse submenu-dark">
							<nav class="nav-main">

								<!-- 
									.nav-onepage
									Required for onepage navigation links
									
									Add .external for an external link!
								-->
								<ul id="topMain" class="nav nav-pills nav-main nav-onepage">
									<li class="active"><!-- HOME -->
										<a id="home-nav" href="index">
											HOME
										</a>
									</li>
									<li><!-- SERVICES -->
										<li class="dropdown">
										<a class="dropdown-toggle" id="services-nav" href="index#services">
										  SERVICES
											</a>
										<ul class="dropdown-menu">
										  <li><a href="residential">Residential</a></li>
										  <li><a href="commercial">Commercial</a></li>
										</ul>
									</li>
									</li>
									<li><!-- PORTFOLIO -->
										<a id="portfolio-nav" href="index#PORTFOLIO">
											PORTFOLIO
										</a>
									</li>
									<li><!-- NEWS -->
										<a id="news-nav" href="index#news">
											NEWS
										</a>
									</li>

									<li><!-- CLIENTS -->
										<a id="clients-nav" href="index#clients">
											CLIENTS
										</a>
									</li>

									<li><!-- CONTACT -->
										<a id="contact-nav" href="index#contact">
											CONTACT
										</a>
									</li>
									<% if user_signed_in? && current_user&.is_employee?(current_user)%>
									<li><!-- INTERVENTIONS -->
										<a id="interventions-nav" href="/interventions">
											INTERVENTIONS
										</a>
									</li>
									<% end %>
									<% if user_signed_in? && current_user&.is_employee?(current_user)%>
									<li><!-- ADMIN -->
										<a id="admin-nav" href="/admin">
											ADMIN
										</a>
									</li>
									<% end %>
									<% if user_signed_in? %> 
                                    <li><!-- USERS logout -->
                                    <%= link_to "SIGN OUT", destroy_user_session_path, :method => :delete %>
                                    </li>
                                    <% else %>
                                    <li><!-- USERS login -->
                                     <%= link_to "LOGIN", new_user_session_path %>
                                    </li>
                                    <% end %>
								</ul>

							</nav>
						</div>

					</div>
				</header>
				<!-- /Top Nav -->

			</div>


			<!-- 
				PAGE HEADER 
				
				CLASSES:
					.page-header-xs	= 20px margins
					.page-header-md	= 50px margins
					.page-header-lg	= 80px margins
					.page-header-xlg= 130px margins
					.dark			= dark page header

					.shadow-before-1 	= shadow 1 header top
					.shadow-after-1 	= shadow 1 header bottom
					.shadow-before-2 	= shadow 2 header top
					.shadow-after-2 	= shadow 2 header bottom
					.shadow-before-3 	= shadow 3 header top
					.shadow-after-3 	= shadow 3 header bottom
			-->
			<!-- /PAGE HEADER -->
			<div >
			<h1 style="text-align:center">Interventions Form<h1>
			</div>
			<!-- Form Section -->
            <div class="text-center">
            <%= render 'form', intervention: @intervention %>

            </div>
			<!-- / -->

			<!-- FOOTER -->
			<footer id="footer">
				<div class="container">


					<div class="row">

						<!-- col #1 -->
						<div class="col-md-8">

							<h3 class="letter-spacing-1">WHY US?</h3>

							<!-- Small Description -->
							<p>
							We have the conviction that we create the most innovative and reliable products on the market. Contact us today for any questions you might have.

							</p>
							<h2>(418) 555-1234</h2>
						</div>
						<!-- /col #1 -->

						
					</div>


				</div>

				<div class="copyright">
					<div class="container">
						<ul class="float-right m-0 list-inline mobile-block">
							<li>Terms &amp; Conditions</li>
							<li>&bull;</li>
							<li>Privacy</li>
						</ul>
						&copy; All Rights Reserved, Rocket Elevators
					</div>
				</div>

			</footer>
			<!-- /FOOTER -->

		<!-- SCROLL TO TOP -->
		<a href="#" id="toTop"></a>



		<!-- JAVASCRIPT FILES -->
		<script>var plugin_path = 'assets/plugins/';</script>
		<%= javascript_include_tag 'scriptsintervention' %>

		

	</body>
</html>

app/views/interventions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @intervention.author %>
</p>

<p>
  <strong>Customerid:</strong>
  <%= @intervention.customerID %>
</p>

<p>
  <strong>Buildingid:</strong>
  <%= @intervention.buildingID %>
</p>

<p>
  <strong>Batteryid:</strong>
  <%= @intervention.batteryID %>
</p>

<p>
  <strong>Columnid:</strong>
  <%= @intervention.columnID %>
</p>

<p>
  <strong>Elevatorid:</strong>
  <%= @intervention.elevatorID %>
</p>

<p>
  <strong>Employeeid:</strong>
  <%= @intervention.employeeID %>
</p>

<p>
  <strong>Start date and time of the intervention:</strong>
  <%= @intervention.start_date_and_time_of_the_intervention %>
</p>

<p>
  <strong>End date and time of the intervention:</strong>
  <%= @intervention.end_date_and_time_of_the_intervention %>
</p>

<p>
  <strong>Result:</strong>
  <%= @intervention.result %>
</p>

<p>
  <strong>Report:</strong>
  <%= @intervention.report %>
</p>

<p>
  <strong>Status:</strong>
  <%= @intervention.status %>
</p>

<%= link_to 'Edit', edit_intervention_path(@intervention) %> |
<%= link_to 'Back', interventions_path %>